//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace CR2ToJPG {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class MainSettings : ApplicationSettingsBase {
        
        private static MainSettings defaultInstance = ((MainSettings)(Synchronized(new MainSettings())));
        
        public static MainSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool allowDuplicates {
            get {
                return ((bool)(this["allowDuplicates"]));
            }
            set {
                this["allowDuplicates"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool allowSubfolders {
            get {
                return ((bool)(this["allowSubfolders"]));
            }
            set {
                this["allowSubfolders"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("100")]
        public double qualityLevel {
            get {
                return ((double)(this["qualityLevel"]));
            }
            set {
                this["qualityLevel"] = value;
            }
        }
    }
}
